# Generated by Django 4.2.5 on 2024-09-18 10:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='category_images')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=100, verbose_name='Издательство')),
                ('language', models.CharField(choices=[('RU', 'Русский'), ('KZ', 'Казахский'), ('EN', 'Английский'), ('OT', 'Другой')], max_length=2, verbose_name='Язык')),
                ('condition', models.CharField(choices=[('Н', 'Новая'), ('О', 'Отличное'), ('Х', 'Хорошее'), ('С', 'Среднее'), ('П', 'Плохое')], max_length=1, verbose_name='Состояние книги')),
                ('cover_type', models.CharField(choices=[('Т', 'Твердый переплет'), ('М', 'Мягкая обложка'), ('К', 'Переплет из картона'), ('И', 'Интегральный переплет'), ('С', 'Суперобложка'), ('Д', 'Другой')], max_length=1, verbose_name='Переплет')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('is_sold', models.BooleanField(default=False)),
                ('is_swap', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
